// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flashcard_study/app/data/models/flash_card.dart';
import 'package:flashcard_study/app/data/models/flash_deck.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FlashCardAdapter());
    registerAdapter(FlashDeckAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FlashCardAdapter());
    registerAdapter(FlashDeckAdapter());
  }
}
