import 'dart:ui';

import 'package:get/get.dart';

class Languages extends Translations {
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ko'),
    Locale('ja'),
    Locale('de'),
    Locale('ru'),
    Locale('fr'),
    Locale('es'),
    Locale('pt'),
    Locale('id'),
    Locale('zh'),
    Locale('ar'),
  ];

  @override
  Map<String, Map<String, String>> get keys => {
    'en': _en,
    'ko': _ko,
    'ja': _ja,
    'de': _de,
    'ru': _ru,
    'fr': _fr,
    'es': _es,
    'pt': _pt,
    'id': _id,
    'zh': _zh,
    'ar': _ar,
  };

  static const Map<String, String> _en = {
    'settings': 'Settings',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'share': 'Share',
    'reset': 'Reset',
    'done': 'Done',
    'ok': 'OK',
    'yes': 'Yes',
    'no': 'No',
    'error': 'Error',
    'success': 'Done',
    'loading': 'Loading...',
    'no_data': 'No data yet.',
    'open_history': 'History',
    'open_stats': 'Stats',
    'refresh': 'Refresh',
    'clear_all': 'Clear All',
    'no_history': 'No history yet.',
    'unknown_event': 'Unknown activity',
    'history_subtitle': 'Screen: @screen / Route: @route',
    'total_events': 'Total Events',
    'today_events': 'Today',
    'week_events': 'This Week',
    'unique_routes': 'Routes',
    'unique_screens': 'Screens',
    'top_events': 'Top Events',
    'dark_mode': 'Dark Mode',
    'language': 'Language',
    'about': 'About',
    'version': 'Version',
    'rate_app': 'Rate this App',
    'privacy_policy': 'Privacy Policy',
    'remove_ads': 'Remove Ads',
    'premium_title': 'Premium',
    'premium_subtitle': 'Go ad-free and unlock every feature.',
    'premium_benefits': 'Premium Benefits',
    'premium_benefit_remove_ads': 'Remove ads',
    'premium_benefit_unlimited': 'Use all features without limits',
    'premium_benefit_statistics': 'View additional statistics',
    'premium_plan_title': 'Choose a plan',
    'premium_plan_weekly': 'Weekly',
    'premium_plan_weekly_desc': '1 week premium access',
    'premium_plan_monthly': 'Monthly',
    'premium_plan_monthly_desc': '30 days premium access',
    'premium_plan_yearly': 'Yearly',
    'premium_plan_yearly_desc': '365 days premium access',
    'premium_purchase': 'Start Premium',
    'premium_restore': 'Restore purchases',
    'premium_owned': 'Premium is active',
    'premium_purchase_note':
        'If your payment is completed, purchase will be restored automatically after app restart.',
    'purchase_error':
        'We couldn\'t complete your purchase. Please try again in a moment.',
    'purchase_unavailable':
        'In-app purchases aren\'t available right now. Please try again in a moment.',
    'purchase_failed':
        'We couldn\'t complete your purchase. Please try again in a moment.',
    'restore_error':
        'We couldn\'t restore your purchase yet. Please try again in a moment.',
    'purchase_success': 'Purchase complete.',
    'premium_ready': 'Premium is ready.',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'Send Feedback',
    'more_apps': 'See More Apps',
    'app_name': 'Flashcard Study',
    'history': 'History',
    'stats': 'Stats',
    'settings_page': 'Settings',
    'no_decks': 'No decks yet',
    'no_decks_sub': 'Create a deck to start studying!',
    'new_deck': 'New Deck',
    'edit_deck': 'Edit Deck',
    'delete_deck': 'Delete Deck',
    'delete_deck_confirm': 'Delete "{title}" and all its cards?',
    'deck_title': 'Deck Title',
    'deck_desc': 'Description (optional)',
    'deck': 'Deck',
    'cards': 'cards',
    'due': 'due',
    'due_today': 'Due Today',
    'total_cards': 'Total',
    'mastered': 'Mastered',
    'no_cards': 'No cards yet',
    'add_card': 'Add Card',
    'edit_card': 'Edit Card',
    'delete_card': 'Delete Card',
    'delete_card_confirm': 'Delete this card?',
    'front': 'Front',
    'back': 'Back',
    'study_due': 'Study (@{n} due)',
    'card_front': 'QUESTION',
    'card_back': 'ANSWER',
    'tap_to_flip': 'Tap to reveal answer',
    'tap_card_to_flip': 'Tap the card to flip',
    'studying': 'Card',
    'cards_left': 'left',
    'how_well': 'How well did you know this?',
    'rate_again': 'Again',
    'rate_hard': 'Hard',
    'rate_good': 'Good',
    'rate_easy': 'Easy',
    'session_done': 'Session Complete!',
    'result_correct': 'Correct',
    'result_accuracy': 'Accuracy',
    'back_to_deck': 'Back to Deck',
    'study_again': 'Study Again',
    'stats_today': 'Today',
    'stats_streak': 'Streak',
    'stats_overall': 'Overall',
    'stats_weekly_chart': 'Last 7 Days',
    'stats_deck_mastery': 'Deck Mastery',
    'stats_today_cards': 'Cards Studied',
    'stats_mastery_rate': 'Mastery Rate',
    'stats_current_streak': 'Current Streak',
    'stats_longest_streak': 'Longest Streak',
    'stats_total_decks': 'Decks',
    'stats_total_cards': 'Total Cards',
    'templates': 'Templates',
    'templates_desc': 'Watch an ad to add a ready-made deck',
    'template_english': 'English Vocabulary',
    'template_english_desc': '50 basic English words with definitions',
    'template_math': 'Math Facts',
    'template_math_desc': 'Times tables and basic formulas (30 cards)',
    'template_capitals': 'World Capitals',
    'template_capitals_desc': 'Countries and their capital cities (30 cards)',
    'get_item_ad': 'Watch Ad',
    'add_with_ad': 'Add (Watch Ad)',
    'template_preview': 'Preview',
    'sound': 'Sound',
    'sound_desc': 'Play sound effects',
    'haptic': 'Haptic feedback',
    'haptic_desc': 'Vibrate for interactions',
    'ads_consent': 'Advertising consent',
    'ads_consent_desc': 'Use ad personalization preference',
    'dark_mode_desc': 'Use dark theme',
    'clear_data': 'Clear local data',
    'clear_data_desc':
        'Reset sound, haptic, consent, language and history logs.',
    'clear_data_confirm': 'This removes all local settings and logs. Continue?',
    'clear_data_complete': 'All local data has been reset.',
    'confirm': 'Confirm',
    'chart_6d': '6d',
    'chart_5d': '5d',
    'chart_4d': '4d',
    'chart_3d': '3d',
    'chart_2d': '2d',
    'chart_yesterday': 'Yst',
    'chart_today': 'Today',
    'interval_day': '@{n}d',
    'template_already_installed': 'This template has already been added.',
  };

  static const Map<String, String> _ko = {
    'settings': '설정',
    'save': '저장',
    'cancel': '취소',
    'delete': '삭제',
    'edit': '편집',
    'share': '공유',
    'reset': '초기화',
    'done': '완료',
    'ok': '확인',
    'yes': '예',
    'no': '아니요',
    'error': '오류',
    'success': '완료됐어요',
    'loading': '불러오는 중이에요',
    'no_data': '아직 내용이 없어요',
    'open_history': '기록',
    'open_stats': '통계',
    'refresh': '새로고침',
    'clear_all': '전체 삭제',
    'no_history': '아직 기록이 없어요',
    'unknown_event': '알 수 없는 활동',
    'history_subtitle': '화면: @screen / 경로: @route',
    'total_events': '총 이벤트',
    'today_events': '오늘',
    'week_events': '이번 주',
    'unique_routes': '고유 경로',
    'unique_screens': '고유 화면',
    'top_events': '상위 이벤트',
    'dark_mode': '다크 모드',
    'language': '언어',
    'about': '앱 정보',
    'version': '버전',
    'rate_app': '앱 평가하기',
    'privacy_policy': '개인정보 처리방침',
    'remove_ads': '광고 제거',
    'premium_title': '프리미엄',
    'premium_subtitle': '광고 없이 모든 기능을 쓸 수 있어요.',
    'premium_benefits': '프리미엄 혜택',
    'premium_benefit_remove_ads': '광고 제거',
    'premium_benefit_unlimited': '모든 기능 잠금 해제',
    'premium_benefit_statistics': '추가 통계 보기',
    'premium_plan_title': '요금제 선택',
    'premium_plan_weekly': '주간',
    'premium_plan_weekly_desc': '7일 프리미엄',
    'premium_plan_monthly': '월간',
    'premium_plan_monthly_desc': '30일 프리미엄',
    'premium_plan_yearly': '연간',
    'premium_plan_yearly_desc': '365일 프리미엄',
    'premium_purchase': '구매하기',
    'premium_restore': '구매 내역 복원',
    'premium_owned': '프리미엄이 활성화됐어요',
    'premium_purchase_note': '결제가 완료되면 앱 재시작 후에도 자동으로 복원돼요.',
    'purchase_error': '구매를 완료하지 못했어요. 잠시 후 다시 시도해 주세요.',
    'purchase_unavailable': '지금은 인앱 결제를 이용하기 어려워요. 잠시 후 다시 시도해 주세요.',
    'purchase_failed': '결제를 완료하지 못했어요. 잠시 후 다시 시도해 주세요.',
    'restore_error': '구매 내역을 아직 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
    'purchase_success': '구매를 완료했어요.',
    'premium_ready': '프리미엄을 바로 쓸 수 있어요.',
    'dev_premium_on': '[DEV] 프리미엄 OFF → ON',
    'dev_premium_off': '[DEV] 프리미엄 ON → OFF',
    'send_feedback': '의견 보내기',
    'more_apps': '다른 앱 보기',
    'app_name': '플래시카드 학습',
    'history': '기록',
    'stats': '통계',
    'settings_page': '설정',
    'no_decks': '덱이 없습니다',
    'no_decks_sub': '덱을 만들고 학습을 시작해요!',
    'new_deck': '새 덱 만들기',
    'edit_deck': '덱 편집',
    'delete_deck': '덱 삭제',
    'delete_deck_confirm': '"{title}" 덱과 모든 카드를 삭제하나요?',
    'deck_title': '덱 제목',
    'deck_desc': '설명 (선택사항)',
    'deck': '덱',
    'cards': '장',
    'due': '복습',
    'due_today': '오늘 복습',
    'total_cards': '전체',
    'mastered': '완료',
    'no_cards': '카드가 없습니다',
    'add_card': '카드 추가',
    'edit_card': '카드 편집',
    'delete_card': '카드 삭제',
    'delete_card_confirm': '이 카드를 삭제하나요?',
    'front': '앞면',
    'back': '뒷면',
    'study_due': '학습 시작 (@{n}개 복습)',
    'card_front': '질문',
    'card_back': '정답',
    'tap_to_flip': '탭해서 정답 보기',
    'tap_card_to_flip': '카드를 탭해서 뒤집기',
    'studying': '카드',
    'cards_left': '남음',
    'how_well': '얼마나 잘 알고 있었나요?',
    'rate_again': '다시',
    'rate_hard': '어려움',
    'rate_good': '보통',
    'rate_easy': '쉬움',
    'session_done': '학습 완료!',
    'result_correct': '정답',
    'result_accuracy': '정확도',
    'back_to_deck': '덱으로',
    'study_again': '다시 학습',
    'stats_today': '오늘',
    'stats_streak': '연속 학습',
    'stats_overall': '전체 현황',
    'stats_weekly_chart': '최근 7일',
    'stats_deck_mastery': '덱별 숙련도',
    'stats_today_cards': '오늘 학습 카드',
    'stats_mastery_rate': '숙련도',
    'stats_current_streak': '현재 연속',
    'stats_longest_streak': '최장 연속',
    'stats_total_decks': '덱 수',
    'stats_total_cards': '전체 카드',
    'templates': '템플릿',
    'templates_desc': '광고를 보면 완성된 덱을 바로 추가할 수 있어요',
    'template_english': '영어 기초 단어',
    'template_english_desc': '기초 영단어 50개',
    'template_math': '수학 공식',
    'template_math_desc': '구구단 + 기초 공식 30개',
    'template_capitals': '세계 수도',
    'template_capitals_desc': '세계 나라와 수도 30개',
    'get_item_ad': '광고 보기',
    'add_with_ad': '추가 (광고 보기)',
    'template_preview': '미리보기',
    'sound': '소리',
    'sound_desc': '효과음 재생',
    'haptic': '햅틱 피드백',
    'haptic_desc': '상호작용 시 진동',
    'ads_consent': '광고 동의',
    'ads_consent_desc': '맞춤 광고 사용',
    'dark_mode_desc': '어두운 테마 사용',
    'clear_data': '로컬 데이터 초기화',
    'clear_data_desc': '소리, 햅틱, 동의, 언어 및 기록 로그를 초기화합니다.',
    'clear_data_confirm': '모든 로컬 설정과 로그가 삭제됩니다. 계속할까요?',
    'clear_data_complete': '모든 로컬 데이터가 초기화되었습니다.',
    'confirm': '확인',
    'chart_6d': '6일전',
    'chart_5d': '5일전',
    'chart_4d': '4일전',
    'chart_3d': '3일전',
    'chart_2d': '2일전',
    'chart_yesterday': '어제',
    'chart_today': '오늘',
    'interval_day': '@{n}일',
    'template_already_installed': '이미 추가된 템플릿입니다.',
  };

  static const Map<String, String> _ja = {
    'settings': '設定',
    'save': '保存',
    'cancel': 'キャンセル',
    'delete': '削除',
    'edit': '編集',
    'share': '共有',
    'reset': 'リセット',
    'done': '完了',
    'ok': 'OK',
    'yes': 'はい',
    'no': 'いいえ',
    'error': 'エラー',
    'success': '完了',
    'loading': '読み込み中...',
    'no_data': 'まだデータがありません。',
    'open_history': '履歴',
    'open_stats': '統計',
    'refresh': '更新',
    'clear_all': 'すべて削除',
    'no_history': 'まだ履歴がありません。',
    'unknown_event': '不明な活動',
    'history_subtitle': 'スクリーン: @screen / ルート: @route',
    'total_events': '合計イベント',
    'today_events': '今日',
    'week_events': '今週',
    'unique_routes': 'ルート',
    'unique_screens': 'スクリーン',
    'top_events': '上位イベント',
    'dark_mode': 'ダークモード',
    'language': '言語',
    'about': 'アプリ情報',
    'version': 'バージョン',
    'rate_app': 'アプリを評価',
    'privacy_policy': 'プライバシーポリシー',
    'remove_ads': '広告を削除',
    'premium_title': 'プレミアム',
    'premium_subtitle': '広告なしですべての機能をロック解除しましょう。',
    'premium_benefits': 'プレミアム特典',
    'premium_benefit_remove_ads': '広告を削除',
    'premium_benefit_unlimited': 'すべての機能を制限なく使用する',
    'premium_benefit_statistics': '追加の統計を表示する',
    'premium_plan_title': 'プランを選択してください',
    'premium_plan_weekly': '週間',
    'premium_plan_weekly_desc': '1週間のプレミアムアクセス',
    'premium_plan_monthly': '月',
    'premium_plan_monthly_desc': '30 日間のプレミアム アクセス',
    'premium_plan_yearly': '毎年',
    'premium_plan_yearly_desc': '365 日のプレミアムアクセス',
    'premium_purchase': 'プレミアムを始める',
    'premium_restore': '購入を復元',
    'premium_owned': 'Premiumが有効です',
    'premium_purchase_note': '支払いが完了すると、アプリを再起動すると自動的に購入が復元されます。',
    'purchase_error': '購入を完了できませんでした。少し後でもう一度お試しください。',
    'purchase_unavailable': '現在、アプリ内購入は利用できません。しばらくしてからもう一度お試しください。',
    'purchase_failed': '購入を完了できませんでした。少し後でもう一度お試しください。',
    'restore_error': '購入を復元できませんでした。少し後でもう一度お試しください。',
    'purchase_success': '購入完了。',
    'premium_ready': 'プレミアムが完成しました。',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'フィードバックを送信',
    'more_apps': '他のアプリを見る',
    'app_name': 'フラッシュカード学習',
    'history': '履歴',
    'stats': '統計',
    'settings_page': '設定',
    'no_decks': 'まだデッキがありません',
    'no_decks_sub': 'デッキを作って勉強を始めましょう！',
    'new_deck': '新しいデッキ',
    'edit_deck': 'デッキを編集する',
    'delete_deck': 'デッキの削除',
    'delete_deck_confirm': '「{title}」とそのすべてのカードを削除しますか?',
    'deck_title': 'デッキタイトル',
    'deck_desc': '説明 (オプション)',
    'deck': 'デッキ',
    'cards': 'カード',
    'due': '期限の',
    'due_today': '今日が期限',
    'total_cards': '合計',
    'mastered': 'マスター済み',
    'no_cards': 'まだカードがありません',
    'add_card': 'カードを追加',
    'edit_card': 'カードの編集',
    'delete_card': 'カードの削除',
    'delete_card_confirm': 'このカードを削除しますか?',
    'front': 'フロント',
    'back': '戻る',
    'study_due': '研究（@{n}期限）',
    'card_front': '質問',
    'card_back': '答える',
    'tap_to_flip': 'タップすると答えが表示されます',
    'tap_card_to_flip': 'カードをタップして裏返します',
    'studying': 'カード',
    'cards_left': '左',
    'how_well': 'これについてどの程度知っていましたか?',
    'rate_again': 'もう一度',
    'rate_hard': 'むずかしい',
    'rate_good': '良い',
    'rate_easy': 'かんたん',
    'session_done': 'セッション完了!',
    'result_correct': '正しい',
    'result_accuracy': '精度',
    'back_to_deck': 'デッキに戻る',
    'study_again': 'もう一度勉強してください',
    'stats_today': '今日',
    'stats_streak': '連続記録',
    'stats_overall': '全体的に',
    'stats_weekly_chart': '直近7日',
    'stats_deck_mastery': 'デッキマスタリー',
    'stats_today_cards': '研究したカード',
    'stats_mastery_rate': 'マスタリー率',
    'stats_current_streak': '継続日数',
    'stats_longest_streak': '最長連続記録',
    'stats_total_decks': 'デッキ',
    'stats_total_cards': 'カードの合計数',
    'templates': 'テンプレート',
    'templates_desc': '広告を見て既製のデッキを追加してください',
    'template_english': '英語の語彙',
    'template_english_desc': '50の基本的な英単語とその定義',
    'template_math': '数学の事実',
    'template_math_desc': '九九と基本公式（30枚）',
    'template_capitals': '世界の首都',
    'template_capitals_desc': '国とその首都 (30 枚のカード)',
    'get_item_ad': '広告を見る',
    'add_with_ad': '追加（広告を見る）',
    'template_preview': 'プレビュー',
    'sound': 'サウンド',
    'sound_desc': '効果音を再生する',
    'haptic': '触覚フィードバック',
    'haptic_desc': 'インタラクションのための振動',
    'ads_consent': '広告掲載の同意',
    'ads_consent_desc': '広告のパーソナライズ設定を使用する',
    'dark_mode_desc': 'ダークテーマを使用する',
    'clear_data': 'ローカルデータをクリアする',
    'clear_data_desc': 'サウンド、触覚、同意、言語、履歴のログをリセットします。',
    'clear_data_confirm': 'これにより、ローカル設定とログがすべて削除されます。続く？',
    'clear_data_complete': 'すべてのローカル データがリセットされました。',
    'confirm': '確認',
    'chart_6d': '6d',
    'chart_5d': '5d',
    'chart_4d': '4D',
    'chart_3d': '3D',
    'chart_2d': '2次元',
    'chart_yesterday': 'イスト',
    'chart_today': '今日',
    'interval_day': '@{n}d',
    'template_already_installed': 'このテンプレートはすでに追加されています。',
  };

  static const Map<String, String> _de = {
    'settings': 'Einstellungen',
    'save': 'Speichern',
    'cancel': 'Abbrechen',
    'delete': 'Löschen',
    'edit': 'Bearbeiten',
    'share': 'Teilen',
    'reset': 'Zurücksetzen',
    'done': 'Erledigt',
    'ok': 'OK',
    'yes': 'Ja',
    'no': 'Nein',
    'error': 'Fehler',
    'success': 'Erledigt',
    'loading': 'Lädt...',
    'no_data': 'Noch keine Daten.',
    'open_history': 'Verlauf',
    'open_stats': 'Statistik',
    'refresh': 'Aktualisieren',
    'clear_all': 'Alles löschen',
    'no_history': 'Noch kein Verlauf.',
    'unknown_event': 'Unbekannte Aktivität',
    'history_subtitle': 'Bildschirm: @screen / Route: @route',
    'total_events': 'Ereignisse gesamt',
    'today_events': 'Heute',
    'week_events': 'Diese Woche',
    'unique_routes': 'Routen',
    'unique_screens': 'Bildschirme',
    'top_events': 'Top-Ereignisse',
    'dark_mode': 'Dunkler Modus',
    'language': 'Sprache',
    'about': 'Info',
    'version': 'Version',
    'rate_app': 'App bewerten',
    'privacy_policy': 'Datenschutz',
    'remove_ads': 'Werbung entfernen',
    'premium_title': 'Premium',
    'premium_subtitle':
        'Werden Sie werbefrei und schalten Sie alle Funktionen frei.',
    'premium_benefits': 'Premium-Vorteile',
    'premium_benefit_remove_ads': 'Werbung entfernen',
    'premium_benefit_unlimited':
        'Nutzen Sie alle Funktionen ohne Einschränkungen',
    'premium_benefit_statistics': 'Weitere Statistiken anzeigen',
    'premium_plan_title': 'Wählen Sie einen Plan',
    'premium_plan_weekly': 'Woche',
    'premium_plan_weekly_desc': '1 Woche Premium-Zugang',
    'premium_plan_monthly': 'Monat',
    'premium_plan_monthly_desc': '30 Tage Premium-Zugang',
    'premium_plan_yearly': 'Jährlich',
    'premium_plan_yearly_desc': '365 Tage Premium-Zugang',
    'premium_purchase': 'Starten Sie Premium',
    'premium_restore': 'Käufe wiederherstellen',
    'premium_owned': 'Premium ist aktiv',
    'premium_purchase_note':
        'Wenn Ihre Zahlung abgeschlossen ist, wird der Kauf nach dem Neustart der App automatisch wiederhergestellt.',
    'purchase_error':
        'Der Kauf konnte nicht abgeschlossen werden. Bitte später erneut versuchen.',
    'purchase_unavailable':
        'In-App-Käufe sind derzeit nicht verfügbar. Bitte versuchen Sie es gleich noch einmal.',
    'purchase_failed':
        'Der Kauf konnte nicht abgeschlossen werden. Bitte später erneut versuchen.',
    'restore_error':
        'Käufe konnten noch nicht wiederhergestellt werden. Bitte später erneut versuchen.',
    'purchase_success': 'Kauf abgeschlossen.',
    'premium_ready': 'Premium ist fertig.',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'Feedback senden',
    'more_apps': 'Weitere Apps',
    'app_name': 'Karteikartenstudie',
    'history': 'Verlauf',
    'stats': 'Statistik',
    'settings_page': 'Einstellungen',
    'no_decks': 'Noch keine Decks',
    'no_decks_sub': 'Erstellen Sie ein Deck, um mit dem Lernen zu beginnen!',
    'new_deck': 'Neues Deck',
    'edit_deck': 'Deck bearbeiten',
    'delete_deck': 'Deck löschen',
    'delete_deck_confirm': '„{title}“ und alle zugehörigen Karten löschen?',
    'deck_title': 'Decktitel',
    'deck_desc': 'Beschreibung (optional)',
    'deck': 'Deck',
    'cards': 'Karten',
    'due': 'fällig',
    'due_today': 'Heute fällig',
    'total_cards': 'Gesamt',
    'mastered': 'Gemeistert',
    'no_cards': 'Noch keine Karten',
    'add_card': 'Karte hinzufügen',
    'edit_card': 'Karte bearbeiten',
    'delete_card': 'Karte löschen',
    'delete_card_confirm': 'Diese Karte löschen?',
    'front': 'Vorne',
    'back': 'Zurück',
    'study_due': 'Studie (@{n} fällig)',
    'card_front': 'FRAGE',
    'card_back': 'ANTWORT',
    'tap_to_flip': 'Tippen Sie, um die Antwort anzuzeigen',
    'tap_card_to_flip': 'Tippen Sie auf die Karte, um sie umzudrehen',
    'studying': 'Karte',
    'cards_left': 'links',
    'how_well': 'Wie gut wussten Sie das?',
    'rate_again': 'Erneut',
    'rate_hard': 'Schwer',
    'rate_good': 'Gut',
    'rate_easy': 'Leicht',
    'session_done': 'Sitzung abgeschlossen!',
    'result_correct': 'Richtig',
    'result_accuracy': 'Genauigkeit',
    'back_to_deck': 'Zurück an Deck',
    'study_again': 'Studieren Sie noch einmal',
    'stats_today': 'Heute',
    'stats_streak': 'Serie',
    'stats_overall': 'Insgesamt',
    'stats_weekly_chart': 'Letzte 7 Tage',
    'stats_deck_mastery': 'Deck-Meisterschaft',
    'stats_today_cards': 'Karten studiert',
    'stats_mastery_rate': 'Meisterschaftsrate',
    'stats_current_streak': 'Aktuelle Serie',
    'stats_longest_streak': 'Längster Streak',
    'stats_total_decks': 'Decks',
    'stats_total_cards': 'Gesamtkarten',
    'templates': 'Vorlagen',
    'templates_desc':
        'Sehen Sie sich eine Anzeige an, um ein fertiges Deck hinzuzufügen',
    'template_english': 'Englischer Wortschatz',
    'template_english_desc':
        '50 grundlegende englische Wörter mit Definitionen',
    'template_math': 'Mathematische Fakten',
    'template_math_desc': 'Einmaleins und Grundformeln (30 Karten)',
    'template_capitals': 'Hauptstädte der Welt',
    'template_capitals_desc': 'Länder und ihre Hauptstädte (30 Karten)',
    'get_item_ad': 'Anzeige ansehen',
    'add_with_ad': 'Hinzufügen (Anzeige ansehen)',
    'template_preview': 'Vorschau',
    'sound': 'Sound',
    'sound_desc': 'Soundeffekte abspielen',
    'haptic': 'Haptisches Feedback',
    'haptic_desc': 'Für Interaktionen vibrieren',
    'ads_consent': 'Werbeeinwilligung',
    'ads_consent_desc':
        'Verwenden Sie die Einstellung zur Anzeigenpersonalisierung',
    'dark_mode_desc': 'Verwenden Sie ein dunkles Thema',
    'clear_data': 'Lokale Daten löschen',
    'clear_data_desc':
        'Ton-, Haptik-, Einwilligungs-, Sprach- und Verlaufsprotokolle zurücksetzen.',
    'clear_data_confirm':
        'Dadurch werden alle lokalen Einstellungen und Protokolle entfernt. Weitermachen?',
    'clear_data_complete': 'Alle lokalen Daten wurden zurückgesetzt.',
    'confirm': 'Bestätigen',
    'chart_6d': '6d',
    'chart_5d': '5d',
    'chart_4d': '4d',
    'chart_3d': '3d',
    'chart_2d': '2d',
    'chart_yesterday': 'Yst',
    'chart_today': 'Heute',
    'interval_day': '@{n}d',
    'template_already_installed': 'Diese Vorlage wurde bereits hinzugefügt.',
  };

  static const Map<String, String> _ru = {
    'settings': 'Настройки',
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'delete': 'Удалить',
    'edit': 'Изменить',
    'share': 'Поделиться',
    'reset': 'Сброс',
    'done': 'Готово',
    'ok': 'OK',
    'yes': 'Да',
    'no': 'Нет',
    'error': 'Ошибка',
    'success': 'Готово',
    'loading': 'Загрузка...',
    'no_data': 'Пока нет данных.',
    'open_history': 'История',
    'open_stats': 'Статистика',
    'refresh': 'Обновить',
    'clear_all': 'Очистить все',
    'no_history': 'Истории пока нет.',
    'unknown_event': 'Неизвестная активность',
    'history_subtitle': 'Экран: @screen / Маршрут: @route',
    'total_events': 'Всего событий',
    'today_events': 'Сегодня',
    'week_events': 'Эта неделя',
    'unique_routes': 'Маршруты',
    'unique_screens': 'Экраны',
    'top_events': 'Популярные события',
    'dark_mode': 'Темная тема',
    'language': 'Язык',
    'about': 'О приложении',
    'version': 'Версия',
    'rate_app': 'Оценить приложение',
    'privacy_policy': 'Политика конфиденциальности',
    'remove_ads': 'Убрать рекламу',
    'premium_title': 'Премиум',
    'premium_subtitle': 'Освободитесь от рекламы и разблокируйте все функции.',
    'premium_benefits': 'Премиальные преимущества',
    'premium_benefit_remove_ads': 'Убрать рекламу',
    'premium_benefit_unlimited': 'Используйте все функции без ограничений',
    'premium_benefit_statistics': 'Посмотреть дополнительную статистику',
    'premium_plan_title': 'Выберите план',
    'premium_plan_weekly': 'Неделя',
    'premium_plan_weekly_desc': 'Премиум-доступ на 1 неделю',
    'premium_plan_monthly': 'Месяц',
    'premium_plan_monthly_desc': 'Премиум-доступ на 30 дней',
    'premium_plan_yearly': 'Ежегодно',
    'premium_plan_yearly_desc': 'Премиум-доступ на 365 дней',
    'premium_purchase': 'Начать Премиум',
    'premium_restore': 'Восстановить покупки',
    'premium_owned': 'Premium активен',
    'premium_purchase_note':
        'Если ваш платеж будет завершен, покупка будет восстановлена автоматически после перезапуска приложения.',
    'purchase_error': 'Не удалось завершить покупку. Попробуйте позже.',
    'purchase_unavailable':
        'Покупки в приложении сейчас недоступны. Пожалуйста, повторите попытку через минуту.',
    'purchase_failed': 'Не удалось завершить покупку. Попробуйте позже.',
    'restore_error': 'Не удалось восстановить покупку. Попробуйте позже.',
    'purchase_success': 'Покупка завершена.',
    'premium_ready': 'Премиум готов.',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'Отправить отзыв',
    'more_apps': 'Другие приложения',
    'app_name': 'Исследование с помощью карточек',
    'history': 'История',
    'stats': 'Статистика',
    'settings_page': 'Настройки',
    'no_decks': 'Колод пока нет',
    'no_decks_sub': 'Создайте колоду, чтобы начать учиться!',
    'new_deck': 'Новая колода',
    'edit_deck': 'Редактировать колоду',
    'delete_deck': 'Удалить колоду',
    'delete_deck_confirm': 'Удалить «{title}» и все его карточки?',
    'deck_title': 'Название колоды',
    'deck_desc': 'Описание (необязательно)',
    'deck': 'Колода',
    'cards': 'карты',
    'due': 'из-за',
    'due_today': 'Срок оплаты сегодня',
    'total_cards': 'Всего',
    'mastered': 'Освоен',
    'no_cards': 'Карты пока нет',
    'add_card': 'Добавить карту',
    'edit_card': 'Редактировать карту',
    'delete_card': 'Удалить карту',
    'delete_card_confirm': 'Удалить эту карту?',
    'front': 'Фронт',
    'back': 'Назад',
    'study_due': 'Исследование (срок @{n})',
    'card_front': 'ВОПРОС',
    'card_back': 'ОТВЕТ',
    'tap_to_flip': 'Нажмите, чтобы показать ответ',
    'tap_card_to_flip': 'Нажмите на карту, чтобы перевернуть',
    'studying': 'Карта',
    'cards_left': 'ушел',
    'how_well': 'Насколько хорошо ты это знал?',
    'rate_again': 'Снова',
    'rate_hard': 'Сложно',
    'rate_good': 'Хорошо',
    'rate_easy': 'Легко',
    'session_done': 'Сессия завершена!',
    'result_correct': 'Правильно',
    'result_accuracy': 'Точность',
    'back_to_deck': 'Вернуться на палубу',
    'study_again': 'Учиться снова',
    'stats_today': 'Сегодня',
    'stats_streak': 'Серия',
    'stats_overall': 'В целом',
    'stats_weekly_chart': 'Последние 7 дней',
    'stats_deck_mastery': 'Мастерство колоды',
    'stats_today_cards': 'Карты изучены',
    'stats_mastery_rate': 'Уровень мастерства',
    'stats_current_streak': 'Текущая серия',
    'stats_longest_streak': 'Самая длинная серия',
    'stats_total_decks': 'колоды',
    'stats_total_cards': 'Всего карт',
    'templates': 'Шаблоны',
    'templates_desc': 'Посмотрите рекламу, чтобы добавить готовую колоду',
    'template_english': 'Английский словарь',
    'template_english_desc': '50 основных английских слов с определениями',
    'template_math': 'Математические факты',
    'template_math_desc': 'Таблицы умножения и основные формулы (30 карточек)',
    'template_capitals': 'Мировые столицы',
    'template_capitals_desc': 'Страны и их столицы (30 карточек)',
    'get_item_ad': 'Смотреть рекламу',
    'add_with_ad': 'Добавить (смотреть рекламу)',
    'template_preview': 'Предпросмотр',
    'sound': 'Звук',
    'sound_desc': 'Воспроизвести звуковые эффекты',
    'haptic': 'Тактильная обратная связь',
    'haptic_desc': 'Вибрация для взаимодействия',
    'ads_consent': 'Согласие на рекламу',
    'ads_consent_desc': 'Использовать настройки персонализации рекламы',
    'dark_mode_desc': 'Использовать темную тему',
    'clear_data': 'Очистить локальные данные',
    'clear_data_desc':
        'Сброс журналов звука, тактильных ощущений, согласия, языка и истории.',
    'clear_data_confirm':
        'При этом будут удалены все локальные настройки и журналы. Продолжать?',
    'clear_data_complete': 'Все локальные данные были сброшены.',
    'confirm': 'Подтвердить',
    'chart_6d': '6д',
    'chart_5d': '5д',
    'chart_4d': '4д',
    'chart_3d': '3д',
    'chart_2d': '2д',
    'chart_yesterday': 'Ист',
    'chart_today': 'Сегодня',
    'interval_day': '@{n}d',
    'template_already_installed': 'Этот шаблон уже добавлен.',
  };

  static const Map<String, String> _fr = {
    'settings': 'Réglages',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'delete': 'Supprimer',
    'edit': 'Modifier',
    'share': 'Partager',
    'reset': 'Réinitialiser',
    'done': 'Fait',
    'ok': 'OK',
    'yes': 'Oui',
    'no': 'Non',
    'error': 'Erreur',
    'success': 'Fait',
    'loading': 'Chargement...',
    'no_data': 'Aucune donnée.',
    'open_history': 'Historique',
    'open_stats': 'Stats',
    'refresh': 'Actualiser',
    'clear_all': 'Tout effacer',
    'no_history': 'Aucun historique.',
    'unknown_event': 'Activité inconnue',
    'history_subtitle': 'Écran : @screen / Itinéraire : @route',
    'total_events': 'Événements totaux',
    'today_events': 'Aujourd’hui',
    'week_events': 'Cette semaine',
    'unique_routes': 'Itinéraires',
    'unique_screens': 'Écrans',
    'top_events': 'Top événements',
    'dark_mode': 'Mode sombre',
    'language': 'Langue',
    'about': 'À propos',
    'version': 'Version',
    'rate_app': 'Noter cette app',
    'privacy_policy': 'Confidentialité',
    'remove_ads': 'Supprimer les pubs',
    'premium_title': 'Premium',
    'premium_subtitle':
        'Évitez les publicités et débloquez toutes les fonctionnalités.',
    'premium_benefits': 'Avantages premium',
    'premium_benefit_remove_ads': 'Supprimer les pubs',
    'premium_benefit_unlimited':
        'Utilisez toutes les fonctionnalités sans limites',
    'premium_benefit_statistics': 'Afficher des statistiques supplémentaires',
    'premium_plan_title': 'Choisissez un forfait',
    'premium_plan_weekly': 'Semaine',
    'premium_plan_weekly_desc': '1 semaine d\'accès premium',
    'premium_plan_monthly': 'Mois',
    'premium_plan_monthly_desc': '30 jours d\'accès premium',
    'premium_plan_yearly': 'Annuel',
    'premium_plan_yearly_desc': 'Accès premium pendant 365 jours',
    'premium_purchase': 'Démarrer Premium',
    'premium_restore': 'Restaurer les achats',
    'premium_owned': 'Premium est actif',
    'premium_purchase_note':
        'Si votre paiement est effectué, l\'achat sera automatiquement restauré après le redémarrage de l\'application.',
    'purchase_error':
        'Impossible de terminer l achat. Réessayez dans un instant.',
    'purchase_unavailable':
        'Les achats intégrés ne sont pas disponibles pour le moment. Veuillez réessayer dans un instant.',
    'purchase_failed':
        'Impossible de terminer l achat. Réessayez dans un instant.',
    'restore_error':
        'Impossible de restaurer l achat. Réessayez dans un instant.',
    'purchase_success': 'Achat terminé.',
    'premium_ready': 'La prime est prête.',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'Envoyer un avis',
    'more_apps': 'Voir plus apps',
    'app_name': 'Étude de cartes mémoire',
    'history': 'Historique',
    'stats': 'Stats',
    'settings_page': 'Réglages',
    'no_decks': 'Pas encore de decks',
    'no_decks_sub': 'Créez un deck pour commencer à étudier !',
    'new_deck': 'Nouveau pont',
    'edit_deck': 'Modifier le deck',
    'delete_deck': 'Supprimer le pont',
    'delete_deck_confirm': 'Supprimer « {title} » et toutes ses cartes ?',
    'deck_title': 'Titre du pont',
    'deck_desc': 'Description (facultatif)',
    'deck': 'Pont',
    'cards': 'cartes',
    'due': 'dû',
    'due_today': 'À rendre aujourd\'hui',
    'total_cards': 'Total',
    'mastered': 'Maîtrisé',
    'no_cards': 'Pas encore de cartes',
    'add_card': 'Ajouter une carte',
    'edit_card': 'Modifier la carte',
    'delete_card': 'Supprimer la carte',
    'delete_card_confirm': 'Supprimer cette carte ?',
    'front': 'Avant',
    'back': 'Retour',
    'study_due': 'Étude (@{n} due)',
    'card_front': 'QUESTION',
    'card_back': 'RÉPONSE',
    'tap_to_flip': 'Appuyez pour révéler la réponse',
    'tap_card_to_flip': 'Appuyez sur la carte pour la retourner',
    'studying': 'Carte',
    'cards_left': 'à gauche',
    'how_well': 'Dans quelle mesure le saviez-vous ?',
    'rate_again': 'Encore',
    'rate_hard': 'Difficile',
    'rate_good': 'Bon',
    'rate_easy': 'Facile',
    'session_done': 'Session terminée !',
    'result_correct': 'Correct',
    'result_accuracy': 'Précision',
    'back_to_deck': 'Retour au pont',
    'study_again': 'Étudier à nouveau',
    'stats_today': 'Aujourd’hui',
    'stats_streak': 'Série',
    'stats_overall': 'Globalement',
    'stats_weekly_chart': '7 derniers jours',
    'stats_deck_mastery': 'Maîtrise du deck',
    'stats_today_cards': 'Cartes étudiées',
    'stats_mastery_rate': 'Taux de maîtrise',
    'stats_current_streak': 'Série actuelle',
    'stats_longest_streak': 'La plus longue séquence',
    'stats_total_decks': 'Ponts',
    'stats_total_cards': 'Total des cartes',
    'templates': 'Modèles',
    'templates_desc':
        'Regardez une annonce pour ajouter un deck prêt à l\'emploi',
    'template_english': 'Vocabulaire anglais',
    'template_english_desc': '50 mots anglais de base avec définitions',
    'template_math': 'Faits mathématiques',
    'template_math_desc':
        'Tables de multiplication et formules de base (30 cartes)',
    'template_capitals': 'Capitales mondiales',
    'template_capitals_desc': 'Pays et leurs capitales (30 cartes)',
    'get_item_ad': 'Voir une pub',
    'add_with_ad': 'Ajouter (Regarder l\'annonce)',
    'template_preview': 'Aperçu',
    'sound': 'Son',
    'sound_desc': 'Jouer des effets sonores',
    'haptic': 'Retour haptique',
    'haptic_desc': 'Vibrer pour les interactions',
    'ads_consent': 'Consentement à la publicité',
    'ads_consent_desc':
        'Utiliser les préférences de personnalisation des annonces',
    'dark_mode_desc': 'Utiliser un thème sombre',
    'clear_data': 'Effacer les données locales',
    'clear_data_desc':
        'Réinitialisez les journaux sonores, haptiques, de consentement, de langue et d’historique.',
    'clear_data_confirm':
        'Cela supprime tous les paramètres et journaux locaux. Continuer?',
    'clear_data_complete': 'Toutes les données locales ont été réinitialisées.',
    'confirm': 'Confirmer',
    'chart_6d': '6j',
    'chart_5d': '5j',
    'chart_4d': '4j',
    'chart_3d': '3D',
    'chart_2d': '2j',
    'chart_yesterday': 'Yst',
    'chart_today': 'Aujourd’hui',
    'interval_day': '@{n}d',
    'template_already_installed': 'Ce modèle a déjà été ajouté.',
  };

  static const Map<String, String> _es = {
    'settings': 'Ajustes',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'delete': 'Eliminar',
    'edit': 'Editar',
    'share': 'Compartir',
    'reset': 'Reiniciar',
    'done': 'Hechas',
    'ok': 'OK',
    'yes': 'Sí',
    'no': 'No',
    'error': 'Error',
    'success': 'Hechas',
    'loading': 'Cargando...',
    'no_data': 'Aún no hay datos.',
    'open_history': 'Historial',
    'open_stats': 'Estadísticas',
    'refresh': 'Actualizar',
    'clear_all': 'Borrar todo',
    'no_history': 'Aún no hay historial.',
    'unknown_event': 'Actividad desconocida',
    'history_subtitle': 'Pantalla: @screen / Ruta: @route',
    'total_events': 'Eventos totales',
    'today_events': 'Hoy',
    'week_events': 'Esta semana',
    'unique_routes': 'Rutas',
    'unique_screens': 'Pantallas',
    'top_events': 'Eventos principales',
    'dark_mode': 'Modo oscuro',
    'language': 'Idioma',
    'about': 'Acerca de',
    'version': 'Versión',
    'rate_app': 'Calificar app',
    'privacy_policy': 'Privacidad',
    'remove_ads': 'Quitar anuncios',
    'premium_title': 'Premium',
    'premium_subtitle': 'No tenga publicidad y desbloquee todas las funciones.',
    'premium_benefits': 'Beneficios Premium',
    'premium_benefit_remove_ads': 'Quitar anuncios',
    'premium_benefit_unlimited': 'Utilice todas las funciones sin límites',
    'premium_benefit_statistics': 'Ver estadísticas adicionales',
    'premium_plan_title': 'Elige un plan',
    'premium_plan_weekly': 'Semana',
    'premium_plan_weekly_desc': 'Acceso premium de 1 semana',
    'premium_plan_monthly': 'Mes',
    'premium_plan_monthly_desc': 'Acceso premium de 30 días',
    'premium_plan_yearly': 'Anual',
    'premium_plan_yearly_desc': 'Acceso premium de 365 días',
    'premium_purchase': 'Iniciar prima',
    'premium_restore': 'Restaurar compras',
    'premium_owned': 'Premium está activo',
    'premium_purchase_note':
        'Si se completa su pago, la compra se restaurará automáticamente después de reiniciar la aplicación.',
    'purchase_error':
        'No se pudo completar la compra. Inténtalo de nuevo pronto.',
    'purchase_unavailable':
        'Las compras dentro de la aplicación no están disponibles en este momento. Inténtelo de nuevo en un momento.',
    'purchase_failed':
        'No se pudo completar la compra. Inténtalo de nuevo pronto.',
    'restore_error':
        'No se pudo restaurar la compra. Inténtalo de nuevo pronto.',
    'purchase_success': 'Compra completa.',
    'premium_ready': 'La prima está lista.',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'Enviar opinión',
    'more_apps': 'Ver más apps',
    'app_name': 'Estudio de tarjetas didácticas',
    'history': 'Historial',
    'stats': 'Estadísticas',
    'settings_page': 'Ajustes',
    'no_decks': 'Aún no hay mazos',
    'no_decks_sub': '¡Crea una baraja para empezar a estudiar!',
    'new_deck': 'Nueva baraja',
    'edit_deck': 'Editar mazo',
    'delete_deck': 'Eliminar mazo',
    'delete_deck_confirm': '¿Eliminar "{title}" y todas sus tarjetas?',
    'deck_title': 'Título del mazo',
    'deck_desc': 'Descripción (opcional)',
    'deck': 'Cubierta',
    'cards': 'tarjetas',
    'due': 'debido',
    'due_today': 'Vencimiento hoy',
    'total_cards': 'Total',
    'mastered': 'dominado',
    'no_cards': 'Aún no hay tarjetas',
    'add_card': 'Agregar tarjeta',
    'edit_card': 'Editar tarjeta',
    'delete_card': 'Eliminar tarjeta',
    'delete_card_confirm': '¿Eliminar esta tarjeta?',
    'front': 'Frente',
    'back': 'Atrás',
    'study_due': 'Estudio (@{n} pendiente)',
    'card_front': 'PREGUNTA',
    'card_back': 'RESPUESTA',
    'tap_to_flip': 'Toca para revelar la respuesta',
    'tap_card_to_flip': 'Toca la tarjeta para voltear',
    'studying': 'Tarjeta',
    'cards_left': 'izquierda',
    'how_well': '¿Qué tan bien sabías esto?',
    'rate_again': 'Otra vez',
    'rate_hard': 'Difícil',
    'rate_good': 'bueno',
    'rate_easy': 'Fácil',
    'session_done': '¡Sesión completa!',
    'result_correct': 'Correcto',
    'result_accuracy': 'Precisión',
    'back_to_deck': 'Volver a la cubierta',
    'study_again': 'Estudiar de nuevo',
    'stats_today': 'Hoy',
    'stats_streak': 'Racha',
    'stats_overall': 'En general',
    'stats_weekly_chart': 'Últimos 7 días',
    'stats_deck_mastery': 'Dominio del mazo',
    'stats_today_cards': 'Tarjetas estudiadas',
    'stats_mastery_rate': 'Tasa de dominio',
    'stats_current_streak': 'Racha actual',
    'stats_longest_streak': 'Racha más larga',
    'stats_total_decks': 'Cubiertas',
    'stats_total_cards': 'Tarjetas totales',
    'templates': 'Plantillas',
    'templates_desc':
        'Mire un anuncio para agregar una plataforma ya preparada',
    'template_english': 'Vocabulario en inglés',
    'template_english_desc': '50 palabras básicas en inglés con definiciones',
    'template_math': 'Datos matemáticos',
    'template_math_desc':
        'Tablas de multiplicar y fórmulas básicas (30 tarjetas)',
    'template_capitals': 'Capitales mundiales',
    'template_capitals_desc': 'Países y sus capitales (30 cartas)',
    'get_item_ad': 'Ver anuncio',
    'add_with_ad': 'Agregar (ver anuncio)',
    'template_preview': 'Vista previa',
    'sound': 'Sonido',
    'sound_desc': 'Reproducir efectos de sonido',
    'haptic': 'Retroalimentación háptica',
    'haptic_desc': 'Vibrar para interacciones',
    'ads_consent': 'Consentimiento publicitario',
    'ads_consent_desc': 'Usar preferencia de personalización de anuncios',
    'dark_mode_desc': 'Usar tema oscuro',
    'clear_data': 'Borrar datos locales',
    'clear_data_desc':
        'Restablecer los registros de sonido, háptica, consentimiento, idioma e historial.',
    'clear_data_confirm':
        'Esto elimina todas las configuraciones y registros locales. ¿Continuar?',
    'clear_data_complete': 'Se han restablecido todos los datos locales.',
    'confirm': 'Confirmar',
    'chart_6d': '6d',
    'chart_5d': '5d',
    'chart_4d': '4d',
    'chart_3d': '3d',
    'chart_2d': '2d',
    'chart_yesterday': 'Yst',
    'chart_today': 'Hoy',
    'interval_day': '@{n}d',
    'template_already_installed': 'Esta plantilla ya ha sido agregada.',
  };

  static const Map<String, String> _pt = {
    'settings': 'Configurações',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'delete': 'Excluir',
    'edit': 'Editar',
    'share': 'Compartilhar',
    'reset': 'Redefinir',
    'done': 'Feitas',
    'ok': 'OK',
    'yes': 'Sim',
    'no': 'Não',
    'error': 'Erro',
    'success': 'Feitas',
    'loading': 'Carregando...',
    'no_data': 'Ainda sem dados.',
    'open_history': 'Histórico',
    'open_stats': 'Estatísticas',
    'refresh': 'Atualizar',
    'clear_all': 'Limpar tudo',
    'no_history': 'Ainda sem histórico.',
    'unknown_event': 'Atividade desconhecida',
    'history_subtitle': 'Tela: @screen / Rota: @route',
    'total_events': 'Total de eventos',
    'today_events': 'Hoje',
    'week_events': 'Esta semana',
    'unique_routes': 'Rotas',
    'unique_screens': 'Telas',
    'top_events': 'Principais eventos',
    'dark_mode': 'Modo escuro',
    'language': 'Idioma',
    'about': 'Sobre',
    'version': 'Versão',
    'rate_app': 'Avaliar app',
    'privacy_policy': 'Privacidade',
    'remove_ads': 'Remover anúncios',
    'premium_title': 'Premium',
    'premium_subtitle': 'Fique sem anúncios e desbloqueie todos os recursos.',
    'premium_benefits': 'Benefícios Premium',
    'premium_benefit_remove_ads': 'Remover anúncios',
    'premium_benefit_unlimited': 'Use todos os recursos sem limites',
    'premium_benefit_statistics': 'Ver estatísticas adicionais',
    'premium_plan_title': 'Escolha um plano',
    'premium_plan_weekly': 'Semana',
    'premium_plan_weekly_desc': '1 semana de acesso premium',
    'premium_plan_monthly': 'Mês',
    'premium_plan_monthly_desc': '30 dias de acesso premium',
    'premium_plan_yearly': 'Anualmente',
    'premium_plan_yearly_desc': 'Acesso premium de 365 dias',
    'premium_purchase': 'Iniciar Premium',
    'premium_restore': 'Restaurar compras',
    'premium_owned': 'Premium está ativo',
    'premium_purchase_note':
        'Se o seu pagamento for concluído, a compra será restaurada automaticamente após a reinicialização do aplicativo.',
    'purchase_error':
        'Não foi possível concluir a compra. Tente novamente em instantes.',
    'purchase_unavailable':
        'As compras no aplicativo não estão disponíveis no momento. Por favor, tente novamente em alguns instantes.',
    'purchase_failed':
        'Não foi possível concluir a compra. Tente novamente em instantes.',
    'restore_error':
        'Não foi possível restaurar a compra. Tente novamente em instantes.',
    'purchase_success': 'Compra concluída.',
    'premium_ready': 'O prêmio está pronto.',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'Enviar feedback',
    'more_apps': 'Ver mais apps',
    'app_name': 'Estudo de cartão flash',
    'history': 'Histórico',
    'stats': 'Estatísticas',
    'settings_page': 'Configurações',
    'no_decks': 'Ainda não há baralhos',
    'no_decks_sub': 'Crie um baralho para começar a estudar!',
    'new_deck': 'Novo baralho',
    'edit_deck': 'Editar baralho',
    'delete_deck': 'Excluir baralho',
    'delete_deck_confirm': 'Excluir "{title}" e todos os seus cartões?',
    'deck_title': 'Título do deck',
    'deck_desc': 'Descrição (opcional)',
    'deck': 'Convés',
    'cards': 'cartões',
    'due': 'devido',
    'due_today': 'Vencimento hoje',
    'total_cards': 'Total',
    'mastered': 'Dominado',
    'no_cards': 'Ainda não há cartões',
    'add_card': 'Adicionar cartão',
    'edit_card': 'Editar cartão',
    'delete_card': 'Excluir cartão',
    'delete_card_confirm': 'Excluir este cartão?',
    'front': 'Frente',
    'back': 'Voltar',
    'study_due': 'Estudo (@{n} devido)',
    'card_front': 'PERGUNTA',
    'card_back': 'RESPOSTA',
    'tap_to_flip': 'Toque para revelar a resposta',
    'tap_card_to_flip': 'Toque no cartão para virar',
    'studying': 'Cartão',
    'cards_left': 'esquerda',
    'how_well': 'Quão bem você sabia disso?',
    'rate_again': 'De novo',
    'rate_hard': 'Difícil',
    'rate_good': 'Bom',
    'rate_easy': 'Fácil',
    'session_done': 'Sessão concluída!',
    'result_correct': 'Correto',
    'result_accuracy': 'Precisão',
    'back_to_deck': 'De volta ao convés',
    'study_again': 'Estude novamente',
    'stats_today': 'Hoje',
    'stats_streak': 'Sequência',
    'stats_overall': 'Geral',
    'stats_weekly_chart': 'Últimos 7 dias',
    'stats_deck_mastery': 'Maestria de convés',
    'stats_today_cards': 'Cartões estudados',
    'stats_mastery_rate': 'Taxa de domínio',
    'stats_current_streak': 'Sequência atual',
    'stats_longest_streak': 'Sequência mais longa',
    'stats_total_decks': 'Convés',
    'stats_total_cards': 'Total de cartas',
    'templates': 'Modelos',
    'templates_desc': 'Assista a um anúncio para adicionar um deck pronto',
    'template_english': 'Vocabulário Inglês',
    'template_english_desc': '50 palavras básicas em inglês com definições',
    'template_math': 'Fatos matemáticos',
    'template_math_desc': 'Tabuada e fórmulas básicas (30 cartas)',
    'template_capitals': 'Capitais Mundiais',
    'template_capitals_desc': 'Países e suas capitais (30 cartões)',
    'get_item_ad': 'Ver anúncio',
    'add_with_ad': 'Adicionar (assistir ao anúncio)',
    'template_preview': 'Prévia',
    'sound': 'Som',
    'sound_desc': 'Reproduzir efeitos sonoros',
    'haptic': 'Feedback tátil',
    'haptic_desc': 'Vibrar para interações',
    'ads_consent': 'Consentimento de publicidade',
    'ads_consent_desc': 'Usar preferência de personalização de anúncios',
    'dark_mode_desc': 'Usar tema escuro',
    'clear_data': 'Limpar dados locais',
    'clear_data_desc':
        'Redefinir registros de som, sensação tátil, consentimento, idioma e histórico.',
    'clear_data_confirm':
        'Isso remove todas as configurações e registros locais. Continuar?',
    'clear_data_complete': 'Todos os dados locais foram redefinidos.',
    'confirm': 'Confirmar',
    'chart_6d': '6d',
    'chart_5d': '5d',
    'chart_4d': '4d',
    'chart_3d': '3d',
    'chart_2d': '2d',
    'chart_yesterday': 'Primeiro',
    'chart_today': 'Hoje',
    'interval_day': '@{n}d',
    'template_already_installed': 'Este modelo já foi adicionado.',
  };

  static const Map<String, String> _id = {
    'settings': 'Pengaturan',
    'save': 'Simpan',
    'cancel': 'Batal',
    'delete': 'Hapus',
    'edit': 'Edit',
    'share': 'Bagikan',
    'reset': 'Reset',
    'done': 'Selesai',
    'ok': 'OK',
    'yes': 'Ya',
    'no': 'Tidak',
    'error': 'Error',
    'success': 'Selesai',
    'loading': 'Memuat...',
    'no_data': 'Belum ada data.',
    'open_history': 'Riwayat',
    'open_stats': 'Statistik',
    'refresh': 'Muat ulang',
    'clear_all': 'Hapus semua',
    'no_history': 'Belum ada riwayat.',
    'unknown_event': 'Aktivitas tidak dikenal',
    'history_subtitle': 'Layar: @screen / Rute: @route',
    'total_events': 'Total event',
    'today_events': 'Hari ini',
    'week_events': 'Minggu ini',
    'unique_routes': 'Rute',
    'unique_screens': 'Layar',
    'top_events': 'Event teratas',
    'dark_mode': 'Mode gelap',
    'language': 'Bahasa',
    'about': 'Tentang',
    'version': 'Versi',
    'rate_app': 'Beri rating',
    'privacy_policy': 'Privasi',
    'remove_ads': 'Hapus iklan',
    'premium_title': 'Premium',
    'premium_subtitle': 'Bebas iklan dan buka semua fitur.',
    'premium_benefits': 'Manfaat Premi',
    'premium_benefit_remove_ads': 'Hapus iklan',
    'premium_benefit_unlimited': 'Gunakan semua fitur tanpa batas',
    'premium_benefit_statistics': 'Lihat statistik tambahan',
    'premium_plan_title': 'Pilih rencana',
    'premium_plan_weekly': 'Mingguan',
    'premium_plan_weekly_desc': 'Akses premium 1 minggu',
    'premium_plan_monthly': 'Bulanan',
    'premium_plan_monthly_desc': 'Akses premium 30 hari',
    'premium_plan_yearly': 'Tahunan',
    'premium_plan_yearly_desc': 'Akses premium 365 hari',
    'premium_purchase': 'Mulai Premium',
    'premium_restore': 'Pulihkan pembelian',
    'premium_owned': 'Premium aktif',
    'premium_purchase_note':
        'Jika pembayaran Anda selesai, pembelian akan dikembalikan secara otomatis setelah aplikasi dimulai ulang.',
    'purchase_error': 'Pembelian belum selesai. Coba lagi sebentar lagi.',
    'purchase_unavailable':
        'Pembelian dalam aplikasi tidak tersedia saat ini. Silakan coba lagi sebentar lagi.',
    'purchase_failed': 'Pembelian belum selesai. Coba lagi sebentar lagi.',
    'restore_error':
        'Pembelian belum bisa dipulihkan. Coba lagi sebentar lagi.',
    'purchase_success': 'Pembelian selesai.',
    'premium_ready': 'Premi sudah siap.',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'Kirim masukan',
    'more_apps': 'Lihat aplikasi lain',
    'app_name': 'Studi Kartu Flash',
    'history': 'Riwayat',
    'stats': 'Statistik',
    'settings_page': 'Pengaturan',
    'no_decks': 'Belum ada deck',
    'no_decks_sub': 'Buat dek untuk mulai belajar!',
    'new_deck': 'Dek Baru',
    'edit_deck': 'Sunting Dek',
    'delete_deck': 'Hapus Dek',
    'delete_deck_confirm': 'Hapus "{title}" dan semua kartunya?',
    'deck_title': 'Judul Dek',
    'deck_desc': 'Deskripsi (opsional)',
    'deck': 'Dek',
    'cards': 'kartu',
    'due': 'jatuh tempo',
    'due_today': 'Jatuh Tempo Hari Ini',
    'total_cards': 'Total',
    'mastered': 'Dikuasai',
    'no_cards': 'Belum ada kartu',
    'add_card': 'Tambahkan Kartu',
    'edit_card': 'Sunting Kartu',
    'delete_card': 'Hapus Kartu',
    'delete_card_confirm': 'Hapus kartu ini?',
    'front': 'Depan',
    'back': 'Kembali',
    'study_due': 'Belajar (@{n} jatuh tempo)',
    'card_front': 'PERTANYAAN',
    'card_back': 'JAWABAN',
    'tap_to_flip': 'Ketuk untuk mengungkapkan jawaban',
    'tap_card_to_flip': 'Ketuk kartu untuk membalik',
    'studying': 'Kartu',
    'cards_left': 'kiri',
    'how_well': 'Seberapa baik Anda mengetahui hal ini?',
    'rate_again': 'Lagi',
    'rate_hard': 'Sulit',
    'rate_good': 'Bagus',
    'rate_easy': 'Mudah',
    'session_done': 'Sesi selesai!',
    'result_correct': 'Benar',
    'result_accuracy': 'Akurasi',
    'back_to_deck': 'Kembali ke Dek',
    'study_again': 'Belajar Lagi',
    'stats_today': 'Hari ini',
    'stats_streak': 'Streak',
    'stats_overall': 'Secara keseluruhan',
    'stats_weekly_chart': '7 hari terakhir',
    'stats_deck_mastery': 'Penguasaan Dek',
    'stats_today_cards': 'Kartu Dipelajari',
    'stats_mastery_rate': 'Tingkat Penguasaan',
    'stats_current_streak': 'Runtun saat ini',
    'stats_longest_streak': 'Garis Terpanjang',
    'stats_total_decks': 'Dek',
    'stats_total_cards': 'Jumlah Kartu',
    'templates': 'Templat',
    'templates_desc': 'Tonton iklan untuk menambahkan dek yang sudah jadi',
    'template_english': 'Kosakata Bahasa Inggris',
    'template_english_desc': '50 kata dasar bahasa Inggris beserta definisinya',
    'template_math': 'Fakta Matematika',
    'template_math_desc': 'Tabel perkalian dan rumus dasar (30 kartu)',
    'template_capitals': 'Ibukota Dunia',
    'template_capitals_desc': 'Negara dan ibu kotanya (30 kartu)',
    'get_item_ad': 'Tonton iklan',
    'add_with_ad': 'Tambahkan (Tonton Iklan)',
    'template_preview': 'Pratinjau',
    'sound': 'Suara',
    'sound_desc': 'Mainkan efek suara',
    'haptic': 'Umpan balik haptik',
    'haptic_desc': 'Bergetar untuk interaksi',
    'ads_consent': 'Persetujuan periklanan',
    'ads_consent_desc': 'Gunakan preferensi personalisasi iklan',
    'dark_mode_desc': 'Gunakan tema gelap',
    'clear_data': 'Hapus data lokal',
    'clear_data_desc':
        'Setel ulang log suara, haptik, persetujuan, bahasa, dan riwayat.',
    'clear_data_confirm':
        'Ini menghapus semua pengaturan dan log lokal. Melanjutkan?',
    'clear_data_complete': 'Semua data lokal telah diatur ulang.',
    'confirm': 'Konfirmasi',
    'chart_6d': '6d',
    'chart_5d': '5d',
    'chart_4d': '4d',
    'chart_3d': '3d',
    'chart_2d': '2d',
    'chart_yesterday': 'Ya',
    'chart_today': 'Hari ini',
    'interval_day': '@{n}d',
    'template_already_installed': 'Templat ini telah ditambahkan.',
  };

  static const Map<String, String> _zh = {
    'settings': '设置',
    'save': '保存',
    'cancel': '取消',
    'delete': '删除',
    'edit': '编辑',
    'share': '分享',
    'reset': '重置',
    'done': '已完成',
    'ok': '确定',
    'yes': '是',
    'no': '否',
    'error': '错误',
    'success': '已完成',
    'loading': '加载中...',
    'no_data': '暂无数据。',
    'open_history': '记录',
    'open_stats': '统计',
    'refresh': '刷新',
    'clear_all': '全部清除',
    'no_history': '暂无记录。',
    'unknown_event': '未知活动',
    'history_subtitle': '屏幕：@screen / 路线：@route',
    'total_events': '事件总数',
    'today_events': '今天',
    'week_events': '本周',
    'unique_routes': '路线',
    'unique_screens': '屏幕',
    'top_events': '热门事件',
    'dark_mode': '深色模式',
    'language': '语言',
    'about': '关于',
    'version': '版本',
    'rate_app': '评价应用',
    'privacy_policy': '隐私政策',
    'remove_ads': '移除广告',
    'premium_title': '高级',
    'premium_subtitle': '无广告并解锁所有功能。',
    'premium_benefits': '高级福利',
    'premium_benefit_remove_ads': '移除广告',
    'premium_benefit_unlimited': '无限制地使用所有功能',
    'premium_benefit_statistics': '查看更多统计数据',
    'premium_plan_title': '选择一个计划',
    'premium_plan_weekly': '每周',
    'premium_plan_weekly_desc': '1 周高级访问权限',
    'premium_plan_monthly': '每月',
    'premium_plan_monthly_desc': '30 天高级访问权限',
    'premium_plan_yearly': '每年',
    'premium_plan_yearly_desc': '365 天高级访问',
    'premium_purchase': '启动高级版',
    'premium_restore': '恢复购买',
    'premium_owned': 'Premium 已激活',
    'premium_purchase_note': '如果您的付款完成，应用重启后将自动恢复购买。',
    'purchase_error': '无法完成购买。请稍后再试。',
    'purchase_unavailable': '目前无法进行应用内购买。请稍后重试。',
    'purchase_failed': '无法完成购买。请稍后再试。',
    'restore_error': '无法恢复购买。请稍后再试。',
    'purchase_success': '购买完成。',
    'premium_ready': '高级版已准备就绪。',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': '发送反馈',
    'more_apps': '查看更多应用',
    'app_name': '抽认卡学习',
    'history': '记录',
    'stats': '统计',
    'settings_page': '设置',
    'no_decks': '还没有套牌',
    'no_decks_sub': '创建一个套牌开始学习！',
    'new_deck': '新甲板',
    'edit_deck': '编辑牌组',
    'delete_deck': '删除牌组',
    'delete_deck_confirm': '删除“{title}”及其所有卡牌？',
    'deck_title': '卡组标题',
    'deck_desc': '说明（可选）',
    'deck': '甲板',
    'cards': '卡片',
    'due': '由于',
    'due_today': '今天到期',
    'total_cards': '总计',
    'mastered': '掌握',
    'no_cards': '还没有卡',
    'add_card': '添加卡',
    'edit_card': '编辑卡',
    'delete_card': '删除卡',
    'delete_card_confirm': '删除这张卡？',
    'front': '正面',
    'back': '返回',
    'study_due': '研究（@{n}到期）',
    'card_front': '问题',
    'card_back': '答案',
    'tap_to_flip': '点按即可显示答案',
    'tap_card_to_flip': '点击卡片即可翻转',
    'studying': '卡',
    'cards_left': '左',
    'how_well': '您对这一点了解多少？',
    'rate_again': '再来',
    'rate_hard': '困难',
    'rate_good': '好',
    'rate_easy': '简单',
    'session_done': '练习完成!',
    'result_correct': '正确',
    'result_accuracy': '准确度',
    'back_to_deck': '回到甲板',
    'study_again': '再学习',
    'stats_today': '今天',
    'stats_streak': '连续记录',
    'stats_overall': '整体',
    'stats_weekly_chart': '最近7天',
    'stats_deck_mastery': '甲板精通',
    'stats_today_cards': '学习过的卡片',
    'stats_mastery_rate': '精通率',
    'stats_current_streak': '当前连续',
    'stats_longest_streak': '最长连续纪录',
    'stats_total_decks': '甲板',
    'stats_total_cards': '总牌数',
    'templates': '模板',
    'templates_desc': '观看广告以添加现成的套牌',
    'template_english': '英语词汇',
    'template_english_desc': '50 个基本英语单词及其定义',
    'template_math': '数学事实',
    'template_math_desc': '乘法表和基本公式（30张卡）',
    'template_capitals': '世界各国首都',
    'template_capitals_desc': '国家及其首都（30 张卡）',
    'get_item_ad': '观看广告',
    'add_with_ad': '添加（观看广告）',
    'template_preview': '预览',
    'sound': '声音',
    'sound_desc': '播放音效',
    'haptic': '触觉反馈',
    'haptic_desc': '振动进行互动',
    'ads_consent': '广告同意书',
    'ads_consent_desc': '使用广告个性化首选项',
    'dark_mode_desc': '使用深色主题',
    'clear_data': '清除本地数据',
    'clear_data_desc': '重置声音、触觉、同意、语言和历史记录。',
    'clear_data_confirm': '这将删除所有本地设置和日志。继续？',
    'clear_data_complete': '所有本地数据已重置。',
    'confirm': '确认',
    'chart_6d': '6天',
    'chart_5d': '5天',
    'chart_4d': '4天',
    'chart_3d': '3d',
    'chart_2d': '2d',
    'chart_yesterday': 'yst',
    'chart_today': '今天',
    'interval_day': '@{n}d',
    'template_already_installed': '该模板已添加。',
  };

  static const Map<String, String> _ar = {
    'settings': 'الإعدادات',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'edit': 'تعديل',
    'share': 'مشاركة',
    'reset': 'إعادة ضبط',
    'done': 'منجز',
    'ok': 'حسناً',
    'yes': 'نعم',
    'no': 'لا',
    'error': 'خطأ',
    'success': 'منجز',
    'loading': 'جار التحميل...',
    'no_data': 'لا توجد بيانات بعد.',
    'open_history': 'السجل',
    'open_stats': 'الإحصاءات',
    'refresh': 'تحديث',
    'clear_all': 'مسح الكل',
    'no_history': 'لا يوجد سجل بعد.',
    'unknown_event': 'نشاط غير معروف',
    'history_subtitle': 'الشاشة: @screen / الطريق: @route',
    'total_events': 'إجمالي الأحداث',
    'today_events': 'اليوم',
    'week_events': 'هذا الأسبوع',
    'unique_routes': 'الطرق',
    'unique_screens': 'شاشات',
    'top_events': 'أهم الأحداث',
    'dark_mode': 'الوضع الداكن',
    'language': 'اللغة',
    'about': 'حول التطبيق',
    'version': 'الإصدار',
    'rate_app': 'تقييم التطبيق',
    'privacy_policy': 'سياسة الخصوصية',
    'remove_ads': 'إزالة الإعلانات',
    'premium_title': 'مميز',
    'premium_subtitle':
        'استمتع بالإعلانات الخالية من الإعلانات وافتح جميع الميزات.',
    'premium_benefits': 'فوائد متميزة',
    'premium_benefit_remove_ads': 'إزالة الإعلانات',
    'premium_benefit_unlimited': 'استخدم كافة الميزات بلا حدود',
    'premium_benefit_statistics': 'عرض إحصائيات إضافية',
    'premium_plan_title': 'اختر خطة',
    'premium_plan_weekly': 'أسبوعي',
    'premium_plan_weekly_desc': 'وصول مميز لمدة أسبوع واحد',
    'premium_plan_monthly': 'شهري',
    'premium_plan_monthly_desc': 'وصول مميز لمدة 30 يومًا',
    'premium_plan_yearly': 'سنويا',
    'premium_plan_yearly_desc': 'وصول مميز لمدة 365 يومًا',
    'premium_purchase': 'ابدأ بريميوم',
    'premium_restore': 'استعادة المشتريات',
    'premium_owned': 'Premium نشط',
    'premium_purchase_note':
        'إذا اكتملت عملية الدفع، فستتم استعادة عملية الشراء تلقائيًا بعد إعادة تشغيل التطبيق.',
    'purchase_error': 'تعذر إكمال الشراء. حاول بعد قليل.',
    'purchase_unavailable':
        'عمليات الشراء داخل التطبيق غير متاحة حاليًا. الرجاء المحاولة مرة أخرى في لحظة.',
    'purchase_failed': 'تعذر إكمال الشراء. حاول بعد قليل.',
    'restore_error': 'تعذر استعادة الشراء. حاول بعد قليل.',
    'purchase_success': 'اكتمل الشراء.',
    'premium_ready': 'قسط جاهز.',
    'dev_premium_on': '[DEV] Premium OFF → ON',
    'dev_premium_off': '[DEV] Premium ON → OFF',
    'send_feedback': 'إرسال ملاحظات',
    'more_apps': 'عرض المزيد من التطبيقات',
    'app_name': 'دراسة البطاقات التعليمية',
    'history': 'السجل',
    'stats': 'الإحصاءات',
    'settings_page': 'الإعدادات',
    'no_decks': 'لا الطوابق حتى الآن',
    'no_decks_sub': 'إنشاء سطح السفينة لبدء الدراسة!',
    'new_deck': 'سطح السفينة الجديد',
    'edit_deck': 'تحرير سطح السفينة',
    'delete_deck': 'حذف سطح السفينة',
    'delete_deck_confirm': 'هل تريد حذف "{title}" وجميع بطاقاتها؟',
    'deck_title': 'عنوان سطح السفينة',
    'deck_desc': 'الوصف (اختياري)',
    'deck': 'سطح السفينة',
    'cards': 'بطاقات',
    'due': 'بسبب',
    'due_today': 'مستحق اليوم',
    'total_cards': 'الإجمالي',
    'mastered': 'يتقن',
    'no_cards': 'لا توجد بطاقات حتى الآن',
    'add_card': 'أضف بطاقة',
    'edit_card': 'تحرير البطاقة',
    'delete_card': 'حذف البطاقة',
    'delete_card_confirm': 'هل تريد حذف هذه البطاقة؟',
    'front': 'الجبهة',
    'back': 'العودة',
    'study_due': 'الدراسة (مستحق @{n})',
    'card_front': 'سؤال',
    'card_back': 'الإجابة',
    'tap_to_flip': 'انقر للكشف عن الإجابة',
    'tap_card_to_flip': 'اضغط على البطاقة لقلبها',
    'studying': 'بطاقة',
    'cards_left': 'اليسار',
    'how_well': 'إلى أي مدى عرفت هذا؟',
    'rate_again': 'مرة أخرى',
    'rate_hard': 'صعب',
    'rate_good': 'جيد',
    'rate_easy': 'سهل',
    'session_done': 'اكتملت الجلسة!',
    'result_correct': 'صحيح',
    'result_accuracy': 'الدقة',
    'back_to_deck': 'العودة إلى سطح السفينة',
    'study_again': 'الدراسة مرة أخرى',
    'stats_today': 'اليوم',
    'stats_streak': 'السلسلة',
    'stats_overall': 'عموما',
    'stats_weekly_chart': 'آخر 7 أيام',
    'stats_deck_mastery': 'إتقان سطح السفينة',
    'stats_today_cards': 'تمت دراسة البطاقات',
    'stats_mastery_rate': 'معدل الإتقان',
    'stats_current_streak': 'السلسلة الحالية',
    'stats_longest_streak': 'أطول خط',
    'stats_total_decks': 'الطوابق',
    'stats_total_cards': 'إجمالي البطاقات',
    'templates': 'قوالب',
    'templates_desc': 'شاهد إعلانًا لإضافة مجموعة جاهزة',
    'template_english': 'المفردات الإنجليزية',
    'template_english_desc': '50 كلمة إنجليزية أساسية مع تعريفاتها',
    'template_math': 'حقائق الرياضيات',
    'template_math_desc': 'جداول الضرب والصيغ الأساسية (30 بطاقة)',
    'template_capitals': 'عواصم العالم',
    'template_capitals_desc': 'الدول وعواصمها (30 بطاقة)',
    'get_item_ad': 'مشاهدة إعلان',
    'add_with_ad': 'إضافة (شاهد الإعلان)',
    'template_preview': 'معاينة',
    'sound': 'الصوت',
    'sound_desc': 'تشغيل المؤثرات الصوتية',
    'haptic': 'ردود الفعل اللمسية',
    'haptic_desc': 'يهتز للتفاعلات',
    'ads_consent': 'موافقة الإعلان',
    'ads_consent_desc': 'استخدم تفضيلات تخصيص الإعلانات',
    'dark_mode_desc': 'استخدم المظهر الداكن',
    'clear_data': 'مسح البيانات المحلية',
    'clear_data_desc':
        'إعادة تعيين سجلات الصوت واللمس والموافقة واللغة والتاريخ.',
    'clear_data_confirm':
        'يؤدي هذا إلى إزالة جميع الإعدادات والسجلات المحلية. يكمل؟',
    'clear_data_complete': 'تمت إعادة ضبط جميع البيانات المحلية.',
    'confirm': 'تأكيد',
    'chart_6d': '6 د',
    'chart_5d': '5 د',
    'chart_4d': '4 د',
    'chart_3d': '3D',
    'chart_2d': '2د',
    'chart_yesterday': 'YST',
    'chart_today': 'اليوم',
    'interval_day': '@{n}d',
    'template_already_installed': 'تمت إضافة هذا القالب بالفعل.',
  };
}
