// ================================================
// DangunDad Flutter App - translate.dart Template
// ================================================

import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Languages extends Translations {
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ko'),
  ];

  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      // Common
      'settings': 'Settings',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'share': 'Share',
      'reset': 'Reset',
      'done': 'Done',
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',
      'error': 'Error',
      'success': 'Done',
      'loading': 'Loading...',
      'no_data': 'No data yet.',
      'open_history': 'History',
      'open_stats': 'Stats',
      'refresh': 'Refresh',
      'clear_all': 'Clear All',
      'no_history': 'No history yet.',
      'unknown_event': 'Unknown activity',
      'history_subtitle': 'Screen: @screen / Route: @route',
      'total_events': 'Total Events',
      'today_events': 'Today',
      'week_events': 'This Week',
      'unique_routes': 'Routes',
      'unique_screens': 'Screens',
      'top_events': 'Top Events',

      // Settings
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'about': 'About',
      'version': 'Version',
      'rate_app': 'Rate this App',
      'privacy_policy': 'Privacy Policy',
      'remove_ads': 'Remove Ads',
      'premium_title': 'Premium',
      'premium_subtitle': 'Go ad-free and unlock every feature.',
      'premium_benefits': 'Premium Benefits',
      'premium_benefit_remove_ads': 'Remove ads',
      'premium_benefit_unlimited': 'Use all features without limits',
      'premium_benefit_statistics': 'View additional statistics',
      'premium_plan_title': 'Choose a plan',
      'premium_plan_weekly': 'Weekly',
      'premium_plan_weekly_desc': '1 week premium access',
      'premium_plan_monthly': 'Monthly',
      'premium_plan_monthly_desc': '30 days premium access',
      'premium_plan_yearly': 'Yearly',
      'premium_plan_yearly_desc': '365 days premium access',
      'premium_purchase': 'Start Premium',
      'premium_restore': 'Restore purchases',
      'premium_owned': 'Premium is active',
      'premium_purchase_note': 'If your payment is completed, purchase will be restored automatically after app restart.',
      'purchase_error': "We couldn't complete your purchase. Please try again in a moment.",
      'purchase_unavailable': "In-app purchases aren't available right now. Please try again in a moment.",
      'purchase_failed': "We couldn't complete your purchase. Please try again in a moment.",
      'restore_error': "We couldn't restore your purchase yet. Please try again in a moment.",
      'purchase_success': 'Purchase complete.',
      'premium_ready': 'Premium is ready.',
      'dev_premium_on': '[DEV] Premium OFF → ON',
      'dev_premium_off': '[DEV] Premium ON → OFF',

      // Feedback
      'send_feedback': 'Send Feedback',
      'more_apps': 'See More Apps',

      // App-specific
      'app_name': 'Flashcard Study',
      'history': 'History',
      'stats': 'Stats',
      'settings_page': 'Settings',
      'no_decks': 'No decks yet',
      'no_decks_sub': 'Create a deck to start studying!',
      'new_deck': 'New Deck',
      'edit_deck': 'Edit Deck',
      'delete_deck': 'Delete Deck',
      'delete_deck_confirm': 'Delete "{title}" and all its cards?',
      'deck_title': 'Deck Title',
      'deck_desc': 'Description (optional)',
      'deck': 'Deck',
      'cards': 'cards',
      'due': 'due',
      'due_today': 'Due Today',
      'total_cards': 'Total',
      'mastered': 'Mastered',
      'no_cards': 'No cards yet',
      'add_card': 'Add Card',
      'edit_card': 'Edit Card',
      'delete_card': 'Delete Card',
      'delete_card_confirm': 'Delete this card?',
      'front': 'Front',
      'back': 'Back',
      'study_due': 'Study (@{n} due)',
      'card_front': 'QUESTION',
      'card_back': 'ANSWER',
      'tap_to_flip': 'Tap to reveal answer',
      'tap_card_to_flip': 'Tap the card to flip',
      'studying': 'Card',
      'cards_left': 'left',
      'how_well': 'How well did you know this?',
      'rate_again': 'Again',
      'rate_hard': 'Hard',
      'rate_good': 'Good',
      'rate_easy': 'Easy',
      'session_done': 'Session Complete!',
      'result_correct': 'Correct',
      'result_accuracy': 'Accuracy',
      'back_to_deck': 'Back to Deck',
      'study_again': 'Study Again',

      // Stats page
      'stats_today': 'Today',
      'stats_streak': 'Streak',
      'stats_overall': 'Overall',
      'stats_weekly_chart': 'Last 7 Days',
      'stats_deck_mastery': 'Deck Mastery',
      'stats_today_cards': 'Cards Studied',
      'stats_mastery_rate': 'Mastery Rate',
      'stats_current_streak': 'Current Streak',
      'stats_longest_streak': 'Longest Streak',
      'stats_total_decks': 'Decks',
      'stats_total_cards': 'Total Cards',

      // Templates
      'templates': 'Templates',
      'templates_desc': 'Watch an ad to add a ready-made deck',
      'template_english': 'English Vocabulary',
      'template_english_desc': '50 basic English words with definitions',
      'template_math': 'Math Facts',
      'template_math_desc': 'Times tables and basic formulas (30 cards)',
      'template_capitals': 'World Capitals',
      'template_capitals_desc': 'Countries and their capital cities (30 cards)',
      'get_item_ad': 'Watch Ad',
      'add_with_ad': 'Add (Watch Ad)',
      'template_preview': 'Preview',

      // Settings missing keys
      'sound': 'Sound',
      'sound_desc': 'Play sound effects',
      'haptic': 'Haptic feedback',
      'haptic_desc': 'Vibrate for interactions',
      'ads_consent': 'Advertising consent',
      'ads_consent_desc': 'Use ad personalization preference',
      'dark_mode_desc': 'Use dark theme',
      'clear_data': 'Clear local data',
      'clear_data_desc': 'Reset sound, haptic, consent, language and history logs.',
      'clear_data_confirm': 'This removes all local settings and logs. Continue?',
      'clear_data_complete': 'All local data has been reset.',
      'confirm': 'Confirm',

      // Weekly chart i18n
      'chart_6d': '6d',
      'chart_5d': '5d',
      'chart_4d': '4d',
      'chart_3d': '3d',
      'chart_2d': '2d',
      'chart_yesterday': 'Yst',
      'chart_today': 'Today',

      // Interval preview on rating buttons
      'interval_day': '@{n}d',
    },
    'ko': {
      // 공통
      'settings': '설정',
      'save': '저장',
      'cancel': '취소',
      'delete': '삭제',
      'edit': '편집',
      'share': '공유',
      'reset': '초기화',
      'done': '완료',
      'ok': '확인',
      'yes': '예',
      'no': '아니요',
      'error': '오류',
      'success': '완료됐어요',
      'loading': '불러오는 중이에요',
      'no_data': '아직 내용이 없어요',
      'open_history': '기록',
      'open_stats': '통계',
      'refresh': '새로고침',
      'clear_all': '전체 삭제',
      'no_history': '아직 기록이 없어요',
      'unknown_event': '알 수 없는 활동',
      'history_subtitle': '화면: @screen / 경로: @route',
      'total_events': '총 이벤트',
      'today_events': '오늘',
      'week_events': '이번 주',
      'unique_routes': '고유 경로',
      'unique_screens': '고유 화면',
      'top_events': '상위 이벤트',
      // 설정
      'dark_mode': '다크 모드',
      'language': '언어',
      'about': '앱 정보',
      'version': '버전',
      'rate_app': '앱 평가하기',
      'privacy_policy': '개인정보 처리방침',
      'remove_ads': '광고 제거',
      'premium_title': '프리미엄',
      'premium_subtitle': '광고 없이 모든 기능을 쓸 수 있어요.',
      'premium_benefits': '프리미엄 혜택',
      'premium_benefit_remove_ads': '광고 제거',
      'premium_benefit_unlimited': '모든 기능 잠금 해제',
      'premium_benefit_statistics': '추가 통계 보기',
      'premium_plan_title': '요금제 선택',
      'premium_plan_weekly': '주간',
      'premium_plan_weekly_desc': '7일 프리미엄',
      'premium_plan_monthly': '월간',
      'premium_plan_monthly_desc': '30일 프리미엄',
      'premium_plan_yearly': '연간',
      'premium_plan_yearly_desc': '365일 프리미엄',
      'premium_purchase': '구매하기',
      'premium_restore': '구매 내역 복원',
      'premium_owned': '프리미엄이 활성화됐어요',
      'premium_purchase_note': '결제가 완료되면 앱 재시작 후에도 자동으로 복원돼요.',
      'purchase_error': '구매를 완료하지 못했어요. 잠시 후 다시 시도해 주세요.',
      'purchase_unavailable': '지금은 인앱 결제를 이용하기 어려워요. 잠시 후 다시 시도해 주세요.',
      'purchase_failed': '결제를 완료하지 못했어요. 잠시 후 다시 시도해 주세요.',
      'restore_error': '구매 내역을 아직 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
      'purchase_success': '구매를 완료했어요.',
      'premium_ready': '프리미엄을 바로 쓸 수 있어요.',
      'dev_premium_on': '[DEV] 프리미엄 OFF → ON',
      'dev_premium_off': '[DEV] 프리미엄 ON → OFF',
      // 피드백
      'send_feedback': '의견 보내기',
      'more_apps': '다른 앱 보기',
      // 앱 전용
      'app_name': '플래시카드 학습',
      'history': '기록',
      'stats': '통계',
      'settings_page': '설정',
      'no_decks': '덱이 없습니다',
      'no_decks_sub': '덱을 만들고 학습을 시작해요!',
      'new_deck': '새 덱 만들기',
      'edit_deck': '덱 편집',
      'delete_deck': '덱 삭제',
      'delete_deck_confirm': '"{title}" 덱과 모든 카드를 삭제하나요?',
      'deck_title': '덱 제목',
      'deck_desc': '설명 (선택사항)',
      'deck': '덱',
      'cards': '장',
      'due': '복습',
      'due_today': '오늘 복습',
      'total_cards': '전체',
      'mastered': '완료',
      'no_cards': '카드가 없습니다',
      'add_card': '카드 추가',
      'edit_card': '카드 편집',
      'delete_card': '카드 삭제',
      'delete_card_confirm': '이 카드를 삭제하나요?',
      'front': '앞면',
      'back': '뒷면',
      'study_due': '학습 시작 (@{n}개 복습)',
      'card_front': '질문',
      'card_back': '정답',
      'tap_to_flip': '탭해서 정답 보기',
      'tap_card_to_flip': '카드를 탭해서 뒤집기',
      'studying': '카드',
      'cards_left': '남음',
      'how_well': '얼마나 잘 알고 있었나요?',
      'rate_again': '다시',
      'rate_hard': '어려움',
      'rate_good': '보통',
      'rate_easy': '쉬움',
      'session_done': '학습 완료!',
      'result_correct': '정답',
      'result_accuracy': '정확도',
      'back_to_deck': '덱으로',
      'study_again': '다시 학습',

      // 통계 페이지
      'stats_today': '오늘',
      'stats_streak': '연속 학습',
      'stats_overall': '전체 현황',
      'stats_weekly_chart': '최근 7일',
      'stats_deck_mastery': '덱별 숙련도',
      'stats_today_cards': '오늘 학습 카드',
      'stats_mastery_rate': '숙련도',
      'stats_current_streak': '현재 연속',
      'stats_longest_streak': '최장 연속',
      'stats_total_decks': '덱 수',
      'stats_total_cards': '전체 카드',

      // 템플릿
      'templates': '템플릿',
      'templates_desc': '광고를 보면 완성된 덱을 바로 추가할 수 있어요',
      'template_english': '영어 기초 단어',
      'template_english_desc': '기초 영단어 50개',
      'template_math': '수학 공식',
      'template_math_desc': '구구단 + 기초 공식 30개',
      'template_capitals': '세계 수도',
      'template_capitals_desc': '세계 나라와 수도 30개',
      'get_item_ad': '광고 보기',
      'add_with_ad': '추가 (광고 보기)',
      'template_preview': '미리보기',

      // 설정 누락 키
      'sound': '소리',
      'sound_desc': '효과음 재생',
      'haptic': '햅틱 피드백',
      'haptic_desc': '상호작용 시 진동',
      'ads_consent': '광고 동의',
      'ads_consent_desc': '맞춤 광고 사용',
      'dark_mode_desc': '어두운 테마 사용',
      'clear_data': '로컬 데이터 초기화',
      'clear_data_desc': '소리, 햅틱, 동의, 언어 및 기록 로그를 초기화합니다.',
      'clear_data_confirm': '모든 로컬 설정과 로그가 삭제됩니다. 계속할까요?',
      'clear_data_complete': '모든 로컬 데이터가 초기화되었습니다.',
      'confirm': '확인',

      // 주간 차트 다국어
      'chart_6d': '6일전',
      'chart_5d': '5일전',
      'chart_4d': '4일전',
      'chart_3d': '3일전',
      'chart_2d': '2일전',
      'chart_yesterday': '어제',
      'chart_today': '오늘',

      // 평가 버튼 인터벌 미리보기
      'interval_day': '@{n}일',
    },
  };
}



